#!/bin/bash

main_cfg='/etc/ss-tproxy.conf'

while getopts ":s:p:m:k:O:o:G:g:t:" OPT; do
    case $OPT in
        s) addr="$OPTARG";;
        p) port="$OPTARG";;
        m) method="$OPTARG";;
        k) passwd="$OPTARG";;
        O) protocol="$OPTARG";;
        G) protocol_param="$OPTARG";;
        o) obfs="$OPTARG";;
        g) obfs_param="$OPTARG";;
        t) type="$OPTARG";;
        :) echo "missing argument to '-$OPTARG'" 1>&2; exit 1;;
    esac
done

if [ "$type" = 'ss' ]; then
    sed -ri "s@server_use_ssr=.+@server_use_ssr='false'@g" $main_cfg
    if [ -n "$addr" ]; then sed -ri "s@server_addr=.+@server_addr='$addr'@g" $main_cfg; fi
    if [ -n "$port" ]; then sed -ri "s@server_port=.+@server_port='$port'@g" $main_cfg; fi
    if [ -n "$method" ]; then sed -ri "s@server_method=.+@server_method='$method'@g" $main_cfg; fi
    if [ -n "$passwd" ]; then sed -ri "s@server_passwd=.+@server_passwd='$passwd'@g" $main_cfg; fi
    ss-tproxy restart
elif [ "$type" = 'ssr' ]; then
    sed -ri "s@server_use_ssr=.+@server_use_ssr='true'@g" $main_cfg
    if [ -n "$addr" ]; then sed -ri "s@server_addr=.+@server_addr='$addr'@g" $main_cfg; fi
    if [ -n "$port" ]; then sed -ri "s@server_port=.+@server_port='$port'@g" $main_cfg; fi
    if [ -n "$method" ]; then sed -ri "s@server_method=.+@server_method='$method'@g" $main_cfg; fi
    if [ -n "$passwd" ]; then sed -ri "s@server_passwd=.+@server_passwd='$passwd'@g" $main_cfg; fi
    if [ -n "$protocol" ]; then sed -ri "s@server_protocol=.+@server_protocol='$protocol'@g" $main_cfg; fi
    if [ -n "$protocol_param" ]; then sed -ri "s@server_protocol_param=.+@server_protocol_param='$protocol_param'@g" $main_cfg; fi
    if [ -n "$obfs" ]; then sed -ri "s@server_obfs=.+@server_obfs='$obfs'@g" $main_cfg; fi
    if [ -n "$obfs_param" ]; then sed -ri "s@server_obfs_param=.+@server_obfs_param='$obfs_param'@g" $main_cfg; fi
    ss-tproxy restart
else
    echo "invalid type '$type'" 1>&2
    exit 1
fi
